
   export const inputFormElements = {
        'form': {
          'section': [
              {
                name:"registrationNumber", 
                id:"registrationNumber", 
                required:true, 
                fullWidth:true,
                type: 'text',  
                label:"Registration Number",             
              },  
              { 
                name:"passCodeNumber", 
                id:"passCodeNumber", 
                required:false, 
                fullWidth:true, 
                type: 'text',
                label:"Passcode Number", 
              },
              {
                name: 'gender',
                id: 'gender',
                label: 'Gender',
                type: 'select',
                required: false,
                options: ['Male', 'Female'],
              },
              {
                name: 'civilStatus',
                id: 'civilStatus',
                label: 'Civil Status',
                type: 'select',
                required: false,
                options: ['Single', 'Married'],
              },
              
          ],
          'section2': [
            { 
              name:"softSkills", 
              id:"softSkills", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Soft Skills", 
            },
            { 
              name:"hardSkills", 
              id:"hardSkills", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Hard Skills", 
            },
          ],
          'section3': [
            { 
              name:"exam", 
              id:"exam", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Exam", 
            },
            { 
              name:"stream", 
              id:"stream", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Stream", 
            },
            { 
              name:"year", 
              id:"year", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Year", 
            },
          ],
          'section4': [
            { 
              name:"prefix", 
              id:"prefix", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Prefix", 
            },
            { 
              name:"degree", 
              id:"degree", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Degree", 
            },
            { 
              name:"location", 
              id:"location", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Location", 
            },
            { 
              name:"start", 
              id:"start", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Start", 
            },
            { 
              name:"end", 
              id:"end", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"End", 
            },
          ],
          'section5': [
            { 
              name:"course", 
              id:"course", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Course", 
            },
            { 
              name:"institution", 
              id:"institution", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Institution", 
            },
            { 
              name:"location", 
              id:"location", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Location", 
            },
            { 
              name:"start", 
              id:"start", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Start", 
            },
            { 
              name:"end", 
              id:"end", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"End", 
            },
          ],
          'section6': [
            { 
              name:"membership", 
              id:"membership", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Membership", 
            },
            { 
              name:"organization", 
              id:"organization", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Organization", 
            },
            { 
              name:"year", 
              id:"year", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Year", 
            },
          ],
          'section7': [
            { 
              name:"company", 
              id:"company", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Company", 
            },
            { 
              name:"designation", 
              id:"designation", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Designation", 
            },
            { 
              name:"location", 
              id:"location", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Location", 
            },
            { 
              name:"start", 
              id:"start", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Start", 
            },
            { 
              name:"end", 
              id:"end", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"End", 
            },
            { 
              name:"description", 
              id:"description", 
              required:false, 
              fullWidth:true, 
              type: 'quill',
              label:"Description", 
            },
          ],
          'section8': [
            { 
              name:"totalYearsOfExperience", 
              id:"totalYearsOfExperience", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"Total Years of Experience", 
            },
            { 
              name:"itLiteracy", 
              id:"itLiteracy", 
              required:false, 
              fullWidth:true, 
              type: 'text',
              label:"IT Literacy", 
            },
          ],
        }
      }